version: "3"

services:
  # Database
  db:
    image: mysql
    volumes:
      - /home/shayan/Documents/career/workshop/docker-data/wp_mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  #PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite
  # Wordpress
  wp:
    depends_on:
      - db
    image: wordpress
    ports:
      - "8000:80"
    volumes:
      - /home/shayan/Documents/career/workshop/docker-data/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wp_db
    networks:
      - wpsite
networks:
  wpsite:
