import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import "bootstrap/dist/css/bootstrap.css";

export default function Home(props) {
  const router = useRouter();

  return (
    <div className="container">
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Welcome</h1>

      <div className="row">
        <div className="col card mx-3">
          <Link href="/about" passHref className="card-title">
            <a>
              <h3>Who am I?</h3>
            </a>
          </Link>
          <div className="card-body">
            <p>
              My name is <strong>Shayan Sadeghi</strong>.
              <br />
              <br />
              I&apos;m a <strong>Data Scientist</strong> and a{" "}
              <strong>web developer</strong>.
              <br />
              <br />
              To read a brief about me or send me a message use the button
              bellow.
            </p>

            <button
              className="btn btn-primary d-grid"
              onClick={() => router.push("/about")}
            >
              Contact ME
            </button>
          </div>
        </div>

        <div className="col card mx-3">
          <Link href="/posts" passHref className="card-title">
            <a>
              <h3>Last Posts</h3>
            </a>
          </Link>
          <div className="card-body">
            {props.last_posts.map((post) => (
              <Link key={post.id} href={`/posts/${post.id}`} passHref>
                <div className="my-5">
                  <p className="lead text-decoration-underline">
                    {post.title.rendered}
                  </p>
                  <small className="text-muted fw-light">
                    {post.date.slice(0, 10)}
                  </small>
                </div>
              </Link>
            ))}
          </div>
        </div>

        <div className="col card mx-3 ">
          <Link
            className="card-title"
            href="https://github.com/ShayanSadeghi"
            passHref
          >
            <a target="_blank">
              <h3>Github</h3>
            </a>
          </Link>
          {props.pins.map((pin) => (
            <div key={pin.id} className="card my-4 p-2">
              <p className="lead">{pin.title}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const gh = [
    { id: "1", title: "Tick8" },
    { id: "2", title: "NoteApp" },
    { id: "3", title: "xepersian_quickstart" },
  ];

  const last_posts = await (
    await fetch(
      "http://localhost:8000/wp-json/wp/v2/posts?_fields=id,title,date"
    )
  ).json();

  return {
    props: {
      pins: gh,
      last_posts,
    },
  };
}
