import Head from "next/head";
import { useState, useEffect } from "react";
import Spinner from "../components/Spinner";
import Landing_About from "../components/Landing_About";
import Landing_Blog from "../components/Landing_Blog";
import Landing_Projects from "../components/Landing_Projects";

export default function Home(props) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (props.pins && props.last_posts) {
      setTimeout(() => {
        setIsLoading(false);
      }, 250);
    }
  }, [props]);

  return (
    <div>
      <Spinner isLoading={isLoading} />
      <div className="container">
        <Head>
          <title>Next Blog</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1 className="mb-5 py-3">Welcome</h1>
        <Landing_Blog last_posts={props.last_posts} />
        <Landing_About />
        <Landing_Projects pins={props.pins} />
      </div>
    </div>
  );
}

export async function getStaticProps() {
  let gh;
  let last_posts;

  gh = await fetch("http://localhost:3000/api/project")
    .then((res) => res.json())
    .catch((err) => {
      console.log(err);
      return [];
    });

  last_posts = await fetch(
    "http://localhost:8000/wp-json/wp/v2/posts?_fields=id,title,date"
  )
    .then((res) => res.json())
    .catch((err) => {
      console.log(err);
      return [];
    });

  return {
    props: {
      pins: gh,
      last_posts,
    },
  };
}
