import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <h1>Welcome</h1>
    </div>
  );
}
